routes/backend.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\SectionController;
use App\Http\Controllers\Dashboard\DoctorController;
use App\Http\Controllers\Dashboard\SingleServiceController;
use App\Http\Controllers\Dashboard\InsuranceController;
use App\Http\Controllers\Dashboard\AmbulanceController;
use App\Http\Livewire\CreateGroupServices;
use App\Http\Controllers\Dashboard\PatientController;

use App\Http\Controllers\Dashboard\ReceiptAccountController;

use App\Http\Controllers\Dashboard\PaymentAccountController;

Route::get('/Dashboard_Admin',[DashboardController::class,'index']);

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){


    //##################### Dashboard User ####################################
    Route::get('/dashboard/user', function () {
        return view('Dashboard.User.index');
    })->middleware(['auth'])->name('dashboard.user');
    //##########################################################################
    //##################### Dashboard Admin ####################################
    Route::get('/dashboard/admin', function () {
        return view('Dashboard.Admin.index');
    })->middleware(['auth:admin'])->name('dashboard.admin');

    //#############################################################################





    Route::middleware(['auth:admin'])->group(function (){
        //------------------------Section--------------------------------------------
        Route::resource('sections',SectionController::class);
        //----------------------------------------------------------------------------
        //------------------------Doctor-----------------------------------------------------------------------------------
        Route::resource('doctors',DoctorController::class);
        Route::post('update_password', [DoctorController::class, 'update_password'])->name('update_password');
        Route::post('update_status', [DoctorController::class, 'update_status'])->name('update_status');
        //----------------------------------------------------------------------------------------------------------------

        //------------------------Service-----------------------------------------------------------------------------------
        Route::resource('service', SingleServiceController::class);

        //----------------------------------------------------------------------------------------------------------------

        //------------------------------------GroupServices---------------------------------------------------------------
        Route::view('Add_GroupServices','livewire.GroupServices.include_create')->name('Add_GroupServices');
        //------------------------------------------------------------------------------------------------------------------



        //############################# insurance route ##########################################

        Route::resource('insurances', InsuranceController::class);

        //############################# end insurance route ######################################


        //############################# Ambulance route ##########################################

        Route::resource('ambulances', AmbulanceController::class);

        //############################# end insurance route ######################################


        //############################# Patient route ##########################################

        Route::resource('patients', PatientController::class);

        //############################# end insurance route ######################################



        //############################# single_invoices route ##########################################

        Route::view('single_invoices','livewire.single_invoices.index')->name('single_invoices');
        Route::view('print_single_invoices','livewire.single_invoices.print')->name('print_single_invoices');

        //############################# end single_invoices route ######################################







        //############################# Receipt route ##########################################

        Route::resource('receipts', ReceiptAccountController::class);

        //############################# end Receipt route ######################################


        //############################# Payment route ##########################################

      Route::resource('payments', PaymentAccountController::class);

        //############################# end Payment route ######################################



    });
    //-------------------------------------------------------------------------------


    require __DIR__.'/auth.php';

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Models/Section.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;



class Section extends Model implements TranslatableContract
{
    use  Translatable;
    public $translatedAttributes=['name','description'];
    protected  $guarded=[];

    use HasFactory;

    public function  doctors(){
        return $this->hasMany(Doctor::class);
    }


}

app/Http/Controllers/Dashboard/AmbulanceController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Interfaces\Ambulances\AmbulanceRepositoryInterface;

class AmbulanceController extends Controller
{
    private $ambulance;

    public function __construct(AmbulanceRepositoryInterface $ambulance)
    {
        $this->ambulance = $ambulance;
    }

    public function index()
    {
        return  $this->ambulance->index();
    }

    public function create()
    {
        return  $this->ambulance->create();
    }


    public function store(Request $request)
    {
        return  $this->ambulance->store($request);
    }

    public function edit($id)
    {
        return  $this->ambulance->edit($id);
    }


    public function update(Request $request)
    {
        return $this->ambulance->update($request);
    }



    public function destroy(Request $request)
    {
        return $this->ambulance->destroy($request);
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public  function index(){
        return view('Dashboard.index');
    }
}

app/Http/Controllers/Dashboard/DoctorController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Doctors\DoctorRepositoryInterface;
use App\Models\Doctor;
use App\Models\Section;
use Illuminate\Http\Request;

class DoctorController extends Controller
{

    private $Doctors;

    public function __construct(DoctorRepositoryInterface $Doctors)
    {
        $this->Doctors = $Doctors;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->Doctors->index();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->Doctors->create();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $this->Doctors->store($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return $this->Doctors->edit($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return $this->Doctors->update($request);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
       return $this->Doctors->destroy($request);
    }

    public function update_password(Request $request)
    {
      //  return $request->all();
        $this->validate($request, [
            'password' => 'required|min:6|confirmed',
            'password_confirmation' => 'required|min:6'
        ]);

        return $this->Doctors->update_password($request);
    }

    public function update_status(Request $request)
    {
        $this->validate($request, [
            'status' => 'required|in:0,1',
        ]);
        return $this->Doctors->update_status($request);
    }
}

app/Http/Controllers/Dashboard/InsuranceController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Interfaces\Insurances\InsuranceRepositoryInterface;

class InsuranceController extends Controller
{
    private $insurance;

    public function __construct(InsuranceRepositoryInterface $insurance)
    {
        $this->insurance = $insurance;
    }

    public function index()
    {
        return $this->insurance->index();
    }

    public function create()
    {
        return $this->insurance->create();
    }


    public function store(Request $request)
    {
        return $this->insurance->store($request);
    }

    public function edit($id)
    {
        return $this->insurance->edit($id);
    }


    public function update(Request $request)
    {
        return $this->insurance->update($request);
    }



    public function destroy(Request $request)
    {
        return $this->insurance->destroy($request);
    }

}

app/Http/Controllers/Dashboard/PatientController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Interfaces\Patients\PatientRepositoryInterface;

class PatientController extends Controller
{
    private $patient;

    public function __construct(PatientRepositoryInterface $patient)
    {
        $this->patient = $patient;
    }

    public function index()
    {
        return  $this->patient->index();
    }

    public function create()
    {
        return  $this->patient->create();
    }


    public function store(Request $request)
    {
        return  $this->patient->store($request);
    }

    public function edit($id)
    {
        return  $this->patient->edit($id);
    }

    public function show($id)
    {
        return  $this->patient->show($id);
    }


    public function update(Request $request)
    {
        return  $this->patient->update($request);
    }



    public function destroy(Request $request)
    {
        return  $this->patient->destroy($request);
    }

}

app/Http/Controllers/Dashboard/PaymentAccountController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Finance\PaymentRepositoryInterface;
use Illuminate\Http\Request;

class PaymentAccountController extends Controller
{
    private $payment;

    public function __construct(PaymentRepositoryInterface $payment)
    {
        $this->payment = $payment;
    }


    public function index()
    {
        return  $this->payment->index();
    }

    public function create()
    {
        return  $this->payment->create();
    }


    public function store(Request $request)
    {
        return  $this->payment->store($request);
    }


    public function show($id)
    {
        return  $this->payment->show($id);
    }


    public function edit($id)
    {
        return  $this->payment->edit($id);
    }


    public function update(Request $request)
    {
        return  $this->payment->update($request);
    }


    public function destroy(Request $request)
    {
        return  $this->payment->destroy($request);
    }



}

app/Http/Controllers/Dashboard/ReceiptAccountController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Finance\ReceiptRepositoryInterface;
use Illuminate\Http\Request;

class ReceiptAccountController extends Controller
{
    private $receipt;

    public function __construct(ReceiptRepositoryInterface $receipt)
    {
        $this->receipt = $receipt;
    }


    public function index()
    {
        return  $this->receipt->index();
    }

    public function create()
    {
        return  $this->receipt->create();
    }


    public function store(Request $request)
    {
        return  $this->receipt->store($request);
    }


    public function show($id)
    {
        return  $this->receipt->show($id);
    }


    public function edit($id)
    {
        return  $this->receipt->edit($id);
    }


    public function update(Request $request)
    {
        return  $this->receipt->update($request);
    }


    public function destroy(Request $request)
    {
        return  $this->receipt->destroy($request);
    }
}

app/Http/Controllers/Dashboard/SectionController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Sections\SectionRepositoryInterface;
use Illuminate\Http\Request;

class SectionController extends Controller
{
    private $sections;
    public function __construct(SectionRepositoryInterface    $sections )
    {
         $this->sections=$sections;
    }
    public function index()
    {
        return $this->sections->index();
    }
    public function show($id)
    {
        return $this->sections->show($id);
    }
    public function store(Request $request)
    {
        return $this->sections->store($request);
    }
    public function update(Request $request)
    {
        return $this->sections->update($request);
    }
    public function destroy(Request $request)
    {
        return $this->sections->destroy($request);
    }
}

app/Http/Controllers/Dashboard/SingleServiceController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Interfaces\Services\SingleServices\SingleServiceRepositoryInterface;
use Illuminate\Http\Request;

class SingleServiceController extends Controller
{    private $services;
    public function __construct(SingleServiceRepositoryInterface    $services )
    {
        $this->services=$services;
    }
    public function index()
    {
        return   $this->services->index();
    }

    public function store(Request $request)
    {
        return   $this->services->store($request);
    }
    public function update(Request $request)
    {
        return   $this->services->update($request);
    }
    public function destroy(Request $request)
    {
        return   $this->services->destroy($request);
    }
}

resources/views/Dashboard/sections/add.blade.php
<!-- Modal -->
<div class="modal fade" id="add" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{trans('Dashboard/sections_trans.add_sections')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('sections.store') }}" method="post" autocomplete="off">
                @csrf
                <div class="modal-body">
                    @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $properties )
                        <div class="form-group">
                            <label>{{trans('Dashboard/sections_trans.' . $localeCode . '.name_sections')}}</label>
                            <input type="text" name="{{ $localeCode }}[name]" class="form-control" value="{{ old($localeCode . '.name') }}">
                        </div>
                    @endforeach

                    @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $properties )
                            <div class="form-group">
                                <label>{{trans('Dashboard/sections_trans.' . $localeCode . '.description_sections')}}</label>
                                <textarea  name="{{ $localeCode }}[description]" class="form-control" >{{ old($localeCode . '.description') }}</textarea>
                            </div>
                    @endforeach
                    {{--
                    <label for="exampleInputPassword1">{{trans('Dashboard/sections_trans.name_sections')}}</label>
                    <input type="text" name="name" class="form-control">
                    --}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{trans('Dashboard/sections_trans.Close')}}</button>
                    <button type="submit" class="btn btn-primary">{{trans('Dashboard/sections_trans.submit')}}</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Dashboard/sections/delete.blade.php
<!-- Modal -->
<div class="modal fade" id="delete{{ $section->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{trans('Dashboard/sections_trans.delete_sections')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('sections.destroy', 'test') }}" method="post">
                {{ method_field('delete') }}
                {{ csrf_field() }}
                <div class="modal-body">
                    <input type="hidden" name="id" value="{{ $section->id }}">
                    <h5>{{trans('Dashboard/sections_trans.Warning')}}</h5>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{trans('Dashboard/sections_trans.Close')}}</button>
                    <button type="submit" class="btn btn-danger">{{trans('Dashboard/sections_trans.submit')}}</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Dashboard/sections/edit.blade.php
<!-- Modal -->
<div class="modal fade" id="edit{{ $section->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{trans('Dashboard/sections_trans.edit_sections')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('sections.update', 'test') }}" method="post">
                {{ method_field('patch') }}
                {{ csrf_field() }}
                @csrf
                <div class="modal-body">
                    <input type="hidden" name="id" value="{{ $section->id }}">
                    {{--
                 <label for="exampleInputPassword1">{{trans('Dashboard/sections_trans.name_sections')}}</label>


                 <input type="text" name="name" value="{{ $section->name }}" class="form-control">
                 --}}
                    @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $properties )
                        <div class="form-group">
                            <label>{{trans('Dashboard/sections_trans.' . $localeCode . '.name_sections')}}</label>
                            <input type="text" name="{{ $localeCode }}[name]" class="form-control" value="{{  $section->translateOrNew($localeCode)->name }}">
                        </div>
                    @endforeach

                    @foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $properties )
                        <div class="form-group">
                            <label>{{trans('Dashboard/sections_trans.' . $localeCode . '.description_sections')}}</label>
                            <textarea name="{{ $localeCode }}[description]" class="form-control" >{{  $section->translateOrNew($localeCode)->description }}</textarea>
                        </div>
                    @endforeach
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{trans('Dashboard/sections_trans.Close')}}</button>
                    <button type="submit" class="btn btn-primary">{{trans('Dashboard/sections_trans.submit')}}</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Dashboard/sections/show_doctors.blade.php
@extends('Dashboard.layouts.master')
@section('title')
    {{trans('main-sidebar_trans.doctors')}}
@stop
@section('css')
    <link href="{{URL::asset('Dashboard/plugins/datatable/css/dataTables.bootstrap4.min.css')}}" rel="stylesheet" />
    <link href="{{URL::asset('Dashboard/plugins/datatable/css/buttons.bootstrap4.min.css')}}" rel="stylesheet">
    <link href="{{URL::asset('Dashboard/plugins/datatable/css/responsive.bootstrap4.min.css')}}" rel="stylesheet" />
    <link href="{{URL::asset('Dashboard/plugins/datatable/css/jquery.dataTables.min.css')}}" rel="stylesheet">
    <link href="{{URL::asset('Dashboard/plugins/datatable/css/responsive.dataTables.min.css')}}" rel="stylesheet">
    <link href="{{URL::asset('Dashboard/plugins/select2/css/select2.min.css')}}" rel="stylesheet">
    <!--Internal   Notify -->
    <link href="{{URL::asset('dashboard/plugins/notify/css/notifIt.css')}}" rel="stylesheet"/>
    <style>
        .hidden{
            display: none;
        }
    </style>
@endsection


@section('page-header')
    <!-- breadcrumb -->
    <div class="breadcrumb-header justify-content-between">
        <div class="my-auto">
            <div class="d-flex">
                <h4 class="content-title mb-0 my-auto">{{$section->name}}</h4>
                <span class="text-muted mt-1 tx-13 mr-2 mb-0">/{{trans('main-sidebar_trans.doctors')}}</span>
                <span class="text-muted mt-1 tx-13 mr-2 mb-0">/
                    {{trans('main-sidebar_trans.view_all')}}</span>
            </div>
        </div>
    </div>
    <!-- breadcrumb -->
@endsection
@section('content')
    @include('Dashboard.messages_alert')
    <!-- row opened -->
    <div class="row row-sm">
        <!--div-->
        <div class="col-xl-12">
            <div class="card mg-b-20">
                <div class="card-header pb-0">

                    <a href="{{route('doctors.create')}}" class="btn btn-primary" role="button" aria-pressed="true">{{trans('doctors.add_doctor')}}</a>
                    <button class="btn btn-danger delBtn"><i class="fa fa-trash"></i>حذف الكل</button>


                </div>
                <div class="card-body">

                    <form action="{{ route('doctors.destroy', 'test') }}" method="post">
                        {{ method_field('delete') }}
                        {{ csrf_field() }}

                        <div class="table-responsive">
                            <table id="example" class="table key-buttons text-md-nowrap">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th><input type="checkbox" class="check_all" onclick="check_all()"/></th>
                                    <th >{{trans('doctors.doctor_photo')}}</th>
                                    <th >{{trans('doctors.name')}}</th>
                                    <th >{{trans('doctors.email')}}</th>
                                    <th>{{trans('doctors.section')}}</th>
                                    <th >{{trans('doctors.phone')}}</th>
                                    <th >{{trans('doctors.appointments')}}</th>

                                    <th >{{trans('doctors.status')}}</th>
                                    {{--
                                    <th>{{trans('doctors.created_at')}}</th>
                                    --}}
                                    <th>{{trans('doctors.processes')}}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($doctors as $doctor)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>@include('Dashboard.doctors.btns.checkbox')</td>
                                        <td>
                                            @if($doctor->image&&\File::exists('Dashboard/img/doctors/'.$doctor->image->filename))
                                                <img src="{{Url::asset('Dashboard/img/doctors/'.$doctor->image->filename)}}" height="50px" width="50px" alt="">
                                            @else
                                                <img src="{{Url::asset('Dashboard/img/doctor_default.png')}}" height="50px" width="50px" alt="">
                                            @endif
                                        </td>
                                        <td>{{ $doctor->name }}</td>
                                        <td>{{ $doctor->email }}</td>
                                        <td>{{ $doctor->section->name}}</td>
                                        <td>{{ $doctor->phone}}</td>
                                        <td>{{implode(",",$doctor->doctorappointments->pluck('name')->toArray())}}</td>

                                        <td>
                                            <div class="dot-label bg-{{$doctor->status == 1 ? 'success':'danger'}} ml-1"></div>
                                            {{$doctor->status == 1 ? trans('doctors.enabled'):trans('doctors.not_enabled')}}
                                        </td>
                                        {{--
                                        <td>{{ $doctor->created_at->diffForHumans() }}</td>--}}
                                        <td>
                                            <div class="dropdown">
                                                <button aria-expanded="false" aria-haspopup="true" class="btn ripple btn-outline-primary btn-sm" data-toggle="dropdown" type="button">{{trans('doctors.processes')}}<i class="fas fa-caret-down mr-1"></i></button>
                                                <div class="dropdown-menu tx-13">
                                                    <a class="dropdown-item" href="{{route('doctors.edit',$doctor->id)}}"><i style="color: #0ba360" class="text-success ti-user"></i>&nbsp;&nbsp;تعديل البيانات</a>
                                                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#update_password{{$doctor->id}}"><i   class="text-primary ti-key"></i>&nbsp;&nbsp;تغير كلمة المرور</a>
                                                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#update_status{{$doctor->id}}"><i   class="text-warning ti-back-right"></i>&nbsp;&nbsp;تغير الحالة</a>
                                                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete{{$doctor->id}}"><i   class="text-danger  ti-trash"></i>&nbsp;&nbsp;حذف البيانات</a>

                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    @include('Dashboard.doctors.delete')
                                    @include('Dashboard.doctors.update_password')
                                    @include('Dashboard.doctors.update_status')
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </form>
                    @include('Dashboard.doctors.delete_select')


                </div>
            </div>
        </div>
        <!--/div-->
    </div>
    <!-- /row -->
    </div>
    <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
    <!-- Internal Data tables -->
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/dataTables.dataTables.min.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/responsive.dataTables.min.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/jquery.dataTables.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/dataTables.bootstrap4.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/dataTables.buttons.min.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/jszip.min.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/pdfmake.min.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/vfs_fonts.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/buttons.html5.min.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/buttons.print.min.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/buttons.colVis.min.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{URL::asset('Dashboard/plugins/datatable/js/responsive.bootstrap4.min.js')}}"></script>
    <!--Internal  Datatable js -->
    <script src="{{URL::asset('Dashboard/js/table-data.js')}}"></script>

    <!--Internal  Notify js -->
    <script src="{{URL::asset('dashboard/plugins/notify/js/notifIt.js')}}"></script>
    <script src="{{URL::asset('/plugins/notify/js/notifit-custom.js')}}"></script>

@endsection